# Generated by Django 4.0 on 2022-05-07 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContactProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Blog Contact',
                'verbose_name_plural': 'Blog Contact',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.blogcontact',),
        ),
        migrations.CreateModel(
            name='ClinicAddProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Clinic Add',
                'verbose_name_plural': 'Clinic Add',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clinics.clinicadd',),
        ),
        migrations.CreateModel(
            name='ClinicReviewsProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Clinic Reviews',
                'verbose_name_plural': 'Clinic Reviews',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clinics.clinicreviews',),
        ),
        migrations.CreateModel(
            name='ClinicTreatmentLeadsProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Clinic Treatment Leads',
                'verbose_name_plural': 'Clinic Treatment Leads',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clinics.clinictreatmentleads',),
        ),
        migrations.CreateModel(
            name='ContactProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Contacts',
                'verbose_name_plural': 'Contacts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clinics.contact',),
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('searched_treatment', models.CharField(max_length=256)),
                ('price', models.FloatField()),
                ('price_type', models.CharField(blank=True, max_length=256, null=True)),
                ('package_info_1', models.CharField(blank=True, max_length=556, null=True)),
                ('package_info_2', models.CharField(blank=True, max_length=556, null=True)),
                ('package_info_3', models.CharField(blank=True, max_length=556, null=True)),
                ('package_info_4', models.CharField(blank=True, max_length=556, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alltreatments', to='clinics.clinic')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency', to='clinics.currency')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatmentlanguage', to='clinics.language')),
            ],
            options={
                'verbose_name_plural': 'Treatments',
                'ordering': ('-created',),
            },
        ),
    ]
