# Generated by Django 4.0 on 2022-05-07 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('treatment', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctor',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('doctors.doctor',),
        ),
        migrations.CreateModel(
            name='TreatmentProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Treatment',
                'verbose_name_plural': 'Treatment',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('treatment.treatment',),
        ),
        migrations.AddField(
            model_name='country',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_language', to='clinics.language'),
        ),
        migrations.AddField(
            model_name='clinictreatmentleads',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allrequests', to='clinics.clinic'),
        ),
        migrations.AddField(
            model_name='clinicreviews',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allreviews', to='clinics.clinic'),
        ),
        migrations.AddField(
            model_name='clinicimage',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allimages', to='clinics.clinic'),
        ),
        migrations.AddField(
            model_name='cliniccertficates',
            name='certificates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allcertificates', to='clinics.certificates'),
        ),
        migrations.AddField(
            model_name='cliniccertficates',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allcertificatesforclinic', to='clinics.clinic'),
        ),
        migrations.AddField(
            model_name='clinicbeforeafterimage',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allimagesafter', to='clinics.clinic'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allcliniccountry', to='clinics.country'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='language',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='allclinicslanguage', to='clinics.language'),
        ),
        migrations.AlterUniqueTogether(
            name='country',
            unique_together={('name', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='cliniccertficates',
            unique_together={('clinic', 'certificates')},
        ),
        migrations.AlterUniqueTogether(
            name='clinic',
            unique_together={('language', 'code')},
        ),
    ]
