# Generated by Django 3.2.12 on 2022-05-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_auto_20220512_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliniclanguages',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
