# Generated by Django 3.2.12 on 2022-06-10 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_alter_cliniclanguages_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingClinics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=256)),
                ('country', models.CharField(blank=True, max_length=256)),
                ('country_flag', models.CharField(blank=True, max_length=256)),
                ('city', models.CharField(blank=True, max_length=256)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinic_logo/')),
                ('feedback_score', models.IntegerField(blank=True, null=True)),
                ('quality_score', models.IntegerField(blank=True, null=True)),
                ('final_score', models.IntegerField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('old_rank', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_ranking_language', to='clinics.language')),
            ],
            options={
                'verbose_name_plural': 'Clinic Ranking',
                'ordering': ('-created_at',),
            },
        ),
    ]
