# Generated by Django 3.2.12 on 2022-06-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_rankingclinics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingclinics',
            name='country_flag',
            field=models.ImageField(blank=True, null=True, upload_to='country_flag/'),
        ),
    ]
