# Generated by Django 3.2.12 on 2022-06-10 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0007_rankingclinics_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingclinics',
            name='city',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='rankingclinics',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankingclinics',
            name='country',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='rankingclinics',
            name='feedback_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankingclinics',
            name='final_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankingclinics',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_ranking_language', to='clinics.language'),
        ),
        migrations.AlterField(
            model_name='rankingclinics',
            name='quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
