# Generated by Django 3.2.12 on 2022-06-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0008_auto_20220610_0314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rankingclinics',
            options={'ordering': ('rank',), 'verbose_name_plural': 'Clinic Ranking'},
        ),
        migrations.AddField(
            model_name='rankingclinics',
            name='slug',
            field=models.SlugField(blank=True, max_length=256),
        ),
    ]
