# Generated by Django 3.2.12 on 2022-07-15 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0010_auto_20220617_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=256)),
                ('package_price', models.FloatField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allpackagesforclinic', to='clinics.clinic')),
            ],
            options={
                'verbose_name_plural': 'Clinic Package',
                'ordering': ('-created',),
                'unique_together': {('clinic', 'package_name')},
            },
        ),
        migrations.CreateModel(
            name='ClinicPackageBulletPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bullet_point', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allbulletpointsforpackage', to='clinics.clinicpackages')),
            ],
            options={
                'verbose_name_plural': 'Clinic Package Bullet Point',
                'ordering': ('-created',),
                'unique_together': {('package', 'bullet_point')},
            },
        ),
    ]
