# Generated by Django 3.2.12 on 2022-07-15 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0011_clinicpackagebulletpoints_clinicpackages'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicpackages',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allpackagesforlanguage', to='clinics.language'),
        ),
    ]
