# Generated by Django 3.2.12 on 2022-07-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0012_clinicpackages_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
