# Generated by Django 3.2.12 on 2022-05-11 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0001_initial'),
        ('clinics', '0002_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularFooterTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('headline', models.CharField(max_length=256)),
                ('img', models.ImageField(upload_to='popular_footer_treatment/')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='popular_footer_language', to='clinics.language')),
            ],
        ),
        migrations.CreateModel(
            name='PopularFooterTreatmentNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popular_footer_treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allpopularfooternames', to='doctors.popularfootertreatment')),
                ('treatment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allpopularfooternames', to='treatment.treatment')),
            ],
        ),
        migrations.CreateModel(
            name='PopularFooterTreatmentProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Popular Footer Treatment',
                'verbose_name_plural': 'Popular Footer Treatment',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('doctors.popularfootertreatment',),
        ),
    ]
