# Generated by Django 3.2.12 on 2022-05-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_remove_populartreatment_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularfootertreatment',
            name='img',
        ),
        migrations.AddField(
            model_name='populartreatment',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='popular_treatment/'),
        ),
    ]
