# Generated by Django 3.2.12 on 2022-05-11 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_initial'),
        ('doctors', '0004_auto_20220511_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularfootertreatment',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allpopularfootertreatment_country', to='clinics.country'),
        ),
    ]
