# Generated by Django 3.2.12 on 2022-05-12 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_alter_cliniclanguages_name'),
        ('doctors', '0005_popularfootertreatment_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicLanguagesProxy',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Clinic Languages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clinics.cliniclanguages',),
        ),
    ]
