# Generated by Django 3.2.12 on 2022-05-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_cliniclanguagesproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularfootertreatment',
            name='country_flag',
            field=models.ImageField(blank=True, null=True, upload_to='popular_footer_treatment/'),
        ),
    ]
