# Generated by Django 3.2.12 on 2022-07-15 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0011_clinicpackagebulletpoints_clinicpackages'),
        ('doctors', '0007_popularfootertreatment_country_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicPackageBulletPointProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Clinic Package Bullet Point',
                'verbose_name_plural': 'Clinic Package Bullet Points',
                'ordering': ('-created',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clinics.clinicpackagebulletpoints',),
        ),
        migrations.CreateModel(
            name='ClinicPackageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Clinic Package',
                'verbose_name_plural': 'Clinic Packages',
                'ordering': ('-created',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clinics.clinicpackages',),
        ),
    ]
