# Generated by Django 3.2.12 on 2022-07-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_clinicpackagebulletpointproxy_clinicpackageproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='populartreatment',
            name='in_header',
            field=models.BooleanField(default=False),
        ),
    ]
