# Generated by Django 3.2.12 on 2022-07-25 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_auto_20220723_0613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popularfootertreatmentnames',
            options={'verbose_name': 'Treatment', 'verbose_name_plural': 'Treatments'},
        ),
        migrations.AlterModelOptions(
            name='popularfootertreatmentproxy',
            options={'verbose_name': 'Footer Destination', 'verbose_name_plural': 'Footer Destinations'},
        ),
        migrations.AlterModelOptions(
            name='populartreatmentnames',
            options={'verbose_name': 'Treatment', 'verbose_name_plural': 'Treatments'},
        ),
        migrations.AlterModelOptions(
            name='populartreatmentproxy',
            options={'verbose_name': 'Header/Main Page Treatment', 'verbose_name_plural': 'Header/Main Page Treatments'},
        ),
    ]
