# Generated by Django 4.0.6 on 2022-08-03 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0013_country_iso_code'),
        ('doctors', '0011_auto_20220725_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularDestinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=256)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='header_destinations_language', to='clinics.language')),
            ],
        ),
        migrations.CreateModel(
            name='PopularDestinationsCityNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=256)),
                ('popular_destinations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allpopulardestinations', to='doctors.populardestinations')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Citys',
            },
        ),
        migrations.CreateModel(
            name='PopularDestinationsProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Header Destinations',
                'verbose_name_plural': 'Header Destinations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('doctors.populardestinations',),
        ),
    ]
