# Generated by Django 4.0.6 on 2022-08-03 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_populardestinations_populardestinationscitynames_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topdestinationsproxy',
            options={'verbose_name': 'Popular Footer Destinations', 'verbose_name_plural': 'Popular Footer Destinations'},
        ),
        migrations.RenameField(
            model_name='populardestinations',
            old_name='headline',
            new_name='country',
        ),
    ]
