# Generated by Django 4.0.6 on 2022-08-03 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0013_country_iso_code'),
        ('doctors', '0014_rename_country_populardestinations_headline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='populardestinationscitynames',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.RemoveField(
            model_name='populardestinations',
            name='headline',
        ),
        migrations.AddField(
            model_name='populardestinations',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinations_country', to='clinics.country'),
        ),
    ]
