# Generated by Django 4.0.6 on 2022-08-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0015_alter_populardestinationscitynames_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='populardestinationscitynames',
            name='slug',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
