"""
Django settings for medicalSite project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
from django.contrib.messages import constants as messages


MESSAGE_TAGS = {
        messages.DEBUG: 'alert-secondary',
        messages.INFO: 'alert-info',
        messages.SUCCESS: 'alert-success',
        messages.WARNING: 'alert-warning',
        messages.ERROR: 'alert-danger',
 }

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATE_DIR = BASE_DIR / 'templates'   


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-im+587r!27ywuum^ecj6^mjj#r8rk84v+)8&#lk7f5t=^_z2ag'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
if DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = ['www.mytripmed.com', 'mytripmed.com']


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    # to support overridding default adminsite
    "medicalSite.apps.MyAdminConfig",
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mathfilters',
    'tinymce',
    'clinics.apps.ClinicsConfig',
    'doctors.apps.DoctorsConfig',
    'treatment.apps.TreatmentConfig',
    'blog',
    'import_export',
    'columns'
    # 'admin_reorder',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "medicalSite.middleware.UpdateSeenMiddleWare"
    # 'admin_reorder.middleware.ModelAdminReorder',
]

ROOT_URLCONF = 'medicalSite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR,],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'medicalSite.context_processor.currency_processor',
                'medicalSite.context_processor.language_processor',
                'medicalSite.context_processor.popular_footer_treatment',

            ],
        },
    },
]

WSGI_APPLICATION = 'medicalSite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases


if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    #  DATABASES = {
    #     'default': {
    #         'ENGINE': 'mysql.connector.django',
    #         'NAME': 'mytripmed_website',
    #         'USER': 'root',
    #         'PASSWORD': '',#'Gc*H*x8D{F2y',
    #         'HOST': 'localhost',
    #         'PORT': '3306',
    #         'OPTIONS': {
    #             'sql_mode': 'STRICT_ALL_TABLES'
    #         },
    #     }
    # }


else:
    # production database
    DATABASES = {
        'default': {
            'ENGINE': 'mysql.connector.django',
            'NAME': 'mytripmed_website',
            'USER': 'root',
            'PASSWORD': '',#'Gc*H*x8D{F2y',
            'HOST': 'localhost',
            'PORT': '3306',
            'OPTIONS': {
                'sql_mode': 'STRICT_ALL_TABLES',
            },
        }
    }

IMPORT_EXPORT_USE_TRANSACTIONS = False
IMPORT_EXPORT_CHUNK_SIZE = 10000


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'en-us'

LANGUAGES = [
    ('en-us','English'),
    ('fr', 'French'),
    # add arabic language
    ('ar', 'Arabic'),
]

TIME_ZONE = 'UTC'

USE_I18N = True
USE_L10N = False

LANGUAGE_BIDI = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/


if not DEBUG:
    STATIC_URL = '/static/'
    #STATIC_ROOT = os.path.join(BASE_DIR, 'static')

    MEDIA_URL = '/media/'
    #MEDIA_ROOT = os.path.join(BASE_DIR, "media")

    STATIC_ROOT='/home/mytripmed/public_html/static/'
    MEDIA_ROOT='/home/mytripmed/public_html/media'

else:
    
    STATIC_URL = 'static/'
    MEDIA_URL='/media/'
    MEDIA_ROOT= BASE_DIR / 'media'
    STATICFILES_DIRS=[BASE_DIR / 'static']
    STATIC_ROOT=BASE_DIR/'staticfiles'

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale')
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


TINYMCE_DEFAULT_CONFIG = {
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 20,
    'selector': 'textarea',
    'paste_as_text': True,
    'theme': 'silver',
    'plugins': '''
            textcolor save link image media preview codesample contextmenu
            table code lists fullscreen  insertdatetime  nonbreaking
            contextmenu directionality searchreplace wordcount visualblocks
            visualchars code fullscreen autolink lists  charmap print  hr
            anchor paste pagebreak
            ''',
    'toolbar1': '''
            fullscreen preview bold italic underline | fontselect,
            fontsizeselect  | forecolor backcolor | alignleft alignright |
            aligncenter alignjustify | indent outdent | bullist numlist table |
            | link image media | codesample |
            ''',
    'toolbar2': '''
            visualblocks visualchars |
            charmap hr pagebreak nonbreaking anchor |  code |
            ''',
    'contextmenu': 'formats | link image',
    'menubar': True,
    'statusbar': True,
}


# ADMIN_REORDER = (
#     # Keep original label and models
#     # 'clinics',

#     # Rename app
#     'blog',
#     {'app': 'doctors', 'label': 'Setting/Reviews'},
#     {'app': 'treatment', 'label': 'Leads'},
#     {'app': 'clinics', 'label': 'Databases'},
#     'auth',


#     # Reorder app models
#     # {'app': 'auth', 'models': ('auth.User', 'auth.Group')},

#     # Exclude models
#     # {'app': 'clinics', 'models': ('clinics.Clinic', )},

#     # Cross-linked models
#     # {'app': 'auth', 'models': ('auth.User', 'sites.Site')},

#     # models with custom name
#     # {'app': 'auth', 'models': (
#     #     'auth.Group',
#     #     {'model': 'auth.User', 'label': 'Staff'},
#     # )},
# )
